/-
  Translation/ArithUtilsDefs.lean

  LLBCFunDef terms AUTO-GENERATED by charon2lean.py from:
    examples/arith_utils.llbc  (produced by `charon cargo`)

  Do NOT edit this file by hand — regenerate with:
    python3 charon2lean.py examples/arith_utils.llbc \
            LeanPlVerify/Translation/ArithUtilsDefs.lean

  Charon version: 0.1.197
  Crate: arith_utils_verify

  Functions analogous to std::u32 stable API (since Rust 1.73):
    div_ceil     — ceiling division
    abs_diff     — unsigned absolute difference
    midpoint     — overflow-safe midpoint (floor)
    is_pow2      — power-of-two test

  Note: Charon emits DivisionByZero UB-check booleans for rem/div
  (e.g., var7 = (b == 0), always false for constant divisors).
  These dead assignments are kept by charon2lean.py and evaluate
  transparently in evalBinOpPure.
-/

import LeanPlVerify.Translation.Elaborator

namespace LeanPlVerify.LLBC.Charon

open LeanPlVerify.LLBC

def DivCeilFun : LLBCFunDef := {
  name   := "div_ceil"
  params := [⟨1, .uint .U32, some "a"⟩, ⟨2, .uint .U32, some "b"⟩]
  locals := [
    ⟨0, .uint .U32, none⟩,
    ⟨1, .uint .U32, some "a"⟩,
    ⟨2, .uint .U32, some "b"⟩,
    ⟨3, .bool_, none⟩,
    ⟨4, .uint .U32, none⟩,
    ⟨5, .uint .U32, none⟩,
    ⟨6, .uint .U32, none⟩,
    ⟨7, .bool_, none⟩,
    ⟨8, .uint .U32, none⟩,
    ⟨9, .uint .U32, none⟩,
    ⟨10, .bool_, none⟩,
    ⟨11, .uint .U32, none⟩,
    ⟨12, .uint .U32, none⟩,
    ⟨13, .uint .U32, none⟩,
    ⟨14, .bool_, none⟩,
    ⟨15, .int .I32, none⟩]
  retTy  := .uint .U32
  body   :=
    (.assign (.var 5) (.use (.copy (.var 1)))
    (.assign (.var 6) (.use (.copy (.var 2)))
      (.assign (.var 7) (.binOp .eq (.copy (.var 6)) (.const (.uint 0 .U32)))
        (.assign (.var 4) (.binOp .rem (.move_ (.var 5)) (.move_ (.var 6)))
          (.assign (.var 3) (.binOp .eq (.move_ (.var 4)) (.const (.uint 0 .U32)))
            (.seq (.ite (.move_ (.var 3))
                (.assign (.var 8) (.use (.copy (.var 1)))
                (.assign (.var 9) (.use (.copy (.var 2)))
                  (.assign (.var 10) (.binOp .eq (.copy (.var 9)) (.const (.uint 0 .U32)))
                    (.assign (.var 0) (.binOp .div (.move_ (.var 8)) (.move_ (.var 9)))
                      .skip))))
                (.assign (.var 12) (.use (.copy (.var 1)))
                (.assign (.var 13) (.use (.copy (.var 2)))
                  (.assign (.var 14) (.binOp .eq (.copy (.var 13)) (.const (.uint 0 .U32)))
                    (.assign (.var 11) (.binOp .div (.move_ (.var 12)) (.move_ (.var 13)))
                      (.assign (.var 15) (.binOp .add (.copy (.var 11)) (.const (.uint 1 .U32)))
                        (.assign (.var 0) (.use (.move_ (.var 15)))
                          .skip)))))))
              .return_))))))
}

def AbsDiffFun : LLBCFunDef := {
  name   := "abs_diff"
  params := [⟨1, .uint .U32, some "a"⟩, ⟨2, .uint .U32, some "b"⟩]
  locals := [
    ⟨0, .uint .U32, none⟩,
    ⟨1, .uint .U32, some "a"⟩,
    ⟨2, .uint .U32, some "b"⟩,
    ⟨3, .bool_, none⟩,
    ⟨4, .uint .U32, none⟩,
    ⟨5, .uint .U32, none⟩,
    ⟨6, .uint .U32, none⟩,
    ⟨7, .uint .U32, none⟩,
    ⟨8, .int .I32, none⟩,
    ⟨9, .uint .U32, none⟩,
    ⟨10, .uint .U32, none⟩,
    ⟨11, .int .I32, none⟩]
  retTy  := .uint .U32
  body   :=
    (.assign (.var 4) (.use (.copy (.var 1)))
    (.assign (.var 5) (.use (.copy (.var 2)))
      (.assign (.var 3) (.binOp .ge (.move_ (.var 4)) (.move_ (.var 5)))
        (.seq (.ite (.move_ (.var 3))
            (.assign (.var 6) (.use (.copy (.var 1)))
            (.assign (.var 7) (.use (.copy (.var 2)))
              (.assign (.var 8) (.binOp .sub (.copy (.var 6)) (.copy (.var 7)))
                (.assign (.var 0) (.use (.move_ (.var 8)))
                  .skip))))
            (.assign (.var 9) (.use (.copy (.var 2)))
            (.assign (.var 10) (.use (.copy (.var 1)))
              (.assign (.var 11) (.binOp .sub (.copy (.var 9)) (.copy (.var 10)))
                (.assign (.var 0) (.use (.move_ (.var 11)))
                  .skip)))))
          .return_))))
}

def MidpointFun : LLBCFunDef := {
  name   := "midpoint"
  params := [⟨1, .uint .U32, some "a"⟩, ⟨2, .uint .U32, some "b"⟩]
  locals := [
    ⟨0, .uint .U32, none⟩,
    ⟨1, .uint .U32, some "a"⟩,
    ⟨2, .uint .U32, some "b"⟩,
    ⟨3, .uint .U32, none⟩,
    ⟨4, .uint .U32, none⟩,
    ⟨5, .uint .U32, none⟩,
    ⟨6, .bool_, none⟩,
    ⟨7, .uint .U32, none⟩,
    ⟨8, .uint .U32, none⟩,
    ⟨9, .bool_, none⟩,
    ⟨10, .int .I32, none⟩,
    ⟨11, .uint .U32, none⟩,
    ⟨12, .uint .U32, none⟩,
    ⟨13, .uint .U32, none⟩,
    ⟨14, .uint .U32, none⟩,
    ⟨15, .int .I32, none⟩]
  retTy  := .uint .U32
  body   :=
    (.assign (.var 5) (.use (.copy (.var 1)))
    (.assign (.var 6) (.binOp .eq (.const (.uint 2 .U32)) (.const (.uint 0 .U32)))
      (.assign (.var 4) (.binOp .div (.move_ (.var 5)) (.const (.uint 2 .U32)))
        (.assign (.var 8) (.use (.copy (.var 2)))
          (.assign (.var 9) (.binOp .eq (.const (.uint 2 .U32)) (.const (.uint 0 .U32)))
            (.assign (.var 7) (.binOp .div (.move_ (.var 8)) (.const (.uint 2 .U32)))
              (.assign (.var 10) (.binOp .add (.copy (.var 4)) (.copy (.var 7)))
                (.assign (.var 3) (.use (.move_ (.var 10)))
                  (.assign (.var 13) (.use (.copy (.var 1)))
                    (.assign (.var 14) (.use (.copy (.var 2)))
                      (.assign (.var 12) (.binOp .bitAnd (.move_ (.var 13)) (.move_ (.var 14)))
                        (.assign (.var 11) (.binOp .bitAnd (.move_ (.var 12)) (.const (.uint 1 .U32)))
                          (.assign (.var 15) (.binOp .add (.copy (.var 3)) (.copy (.var 11)))
                            (.assign (.var 0) (.use (.move_ (.var 15)))
                              .return_))))))))))))))
}

def IsPow2Fun : LLBCFunDef := {
  name   := "is_pow2"
  params := [⟨1, .uint .U32, some "n"⟩]
  locals := [
    ⟨0, .bool_, none⟩,
    ⟨1, .uint .U32, some "n"⟩,
    ⟨2, .bool_, none⟩,
    ⟨3, .uint .U32, none⟩,
    ⟨4, .uint .U32, none⟩,
    ⟨5, .uint .U32, none⟩,
    ⟨6, .uint .U32, none⟩,
    ⟨7, .uint .U32, none⟩,
    ⟨8, .int .I32, none⟩]
  retTy  := .bool_
  body   :=
    (.assign (.var 3) (.use (.copy (.var 1)))
    (.assign (.var 2) (.binOp .eq (.move_ (.var 3)) (.const (.uint 0 .U32)))
      (.seq (.ite (.move_ (.var 2))
          (.assign (.var 0) (.use (.const (.bool false)))
          .skip)
          (.assign (.var 5) (.use (.copy (.var 1)))
          (.assign (.var 7) (.use (.copy (.var 1)))
            (.assign (.var 8) (.binOp .sub (.copy (.var 7)) (.const (.uint 1 .U32)))
              (.assign (.var 6) (.use (.move_ (.var 8)))
                (.assign (.var 4) (.binOp .bitAnd (.move_ (.var 5)) (.move_ (.var 6)))
                  (.assign (.var 0) (.binOp .eq (.move_ (.var 4)) (.const (.uint 0 .U32)))
                    .skip)))))))
        .return_)))
}

end LeanPlVerify.LLBC.Charon
