/-
  Translation/BitopsDefs.lean

  LLBCFunDef terms AUTO-GENERATED by charon2lean.py from:
    examples/bitops.llbc  (produced by `charon cargo`)

  Do NOT edit this file by hand — regenerate with:
    python3 charon2lean.py examples/bitops.llbc \
            LeanPlVerify/Translation/BitopsDefs.lean

  Charon version: 0.1.197
  Crate: bitops_verify

  Functions: bf_is_empty, bf_contains, bf_intersects,
             bf_union, bf_intersection, bf_symmetric_diff
-/

import LeanPlVerify.Translation.Elaborator

namespace LeanPlVerify.LLBC.Charon

open LeanPlVerify.LLBC

def BfIsEmptyFun : LLBCFunDef := {
  name   := "bf_is_empty"
  params := [⟨1, .uint .U32, some "flags"⟩]
  locals := [
    ⟨0, .bool_, none⟩,
    ⟨1, .uint .U32, some "flags"⟩,
    ⟨2, .uint .U32, none⟩]
  retTy  := .bool_
  body   :=
    (.assign (.var 2) (.use (.copy (.var 1)))
    (.assign (.var 0) (.binOp .eq (.move_ (.var 2)) (.const (.uint 0 .U32)))
      .return_))
}

def BfContainsFun : LLBCFunDef := {
  name   := "bf_contains"
  params := [⟨1, .uint .U32, some "flags"⟩, ⟨2, .uint .U32, some "other"⟩]
  locals := [
    ⟨0, .bool_, none⟩,
    ⟨1, .uint .U32, some "flags"⟩,
    ⟨2, .uint .U32, some "other"⟩,
    ⟨3, .uint .U32, none⟩,
    ⟨4, .uint .U32, none⟩,
    ⟨5, .uint .U32, none⟩,
    ⟨6, .uint .U32, none⟩]
  retTy  := .bool_
  body   :=
    (.assign (.var 4) (.use (.copy (.var 1)))
    (.assign (.var 5) (.use (.copy (.var 2)))
      (.assign (.var 3) (.binOp .bitAnd (.move_ (.var 4)) (.move_ (.var 5)))
        (.assign (.var 6) (.use (.copy (.var 2)))
          (.assign (.var 0) (.binOp .eq (.move_ (.var 3)) (.move_ (.var 6)))
            .return_)))))
}

def BfIntersectsFun : LLBCFunDef := {
  name   := "bf_intersects"
  params := [⟨1, .uint .U32, some "flags"⟩, ⟨2, .uint .U32, some "other"⟩]
  locals := [
    ⟨0, .bool_, none⟩,
    ⟨1, .uint .U32, some "flags"⟩,
    ⟨2, .uint .U32, some "other"⟩,
    ⟨3, .uint .U32, none⟩,
    ⟨4, .uint .U32, none⟩,
    ⟨5, .uint .U32, none⟩]
  retTy  := .bool_
  body   :=
    (.assign (.var 4) (.use (.copy (.var 1)))
    (.assign (.var 5) (.use (.copy (.var 2)))
      (.assign (.var 3) (.binOp .bitAnd (.move_ (.var 4)) (.move_ (.var 5)))
        (.assign (.var 0) (.binOp .ne (.move_ (.var 3)) (.const (.uint 0 .U32)))
          .return_))))
}

def BfUnionFun : LLBCFunDef := {
  name   := "bf_union"
  params := [⟨1, .uint .U32, some "a"⟩, ⟨2, .uint .U32, some "b"⟩]
  locals := [
    ⟨0, .uint .U32, none⟩,
    ⟨1, .uint .U32, some "a"⟩,
    ⟨2, .uint .U32, some "b"⟩,
    ⟨3, .uint .U32, none⟩,
    ⟨4, .uint .U32, none⟩]
  retTy  := .uint .U32
  body   :=
    (.assign (.var 3) (.use (.copy (.var 1)))
    (.assign (.var 4) (.use (.copy (.var 2)))
      (.assign (.var 0) (.binOp .bitOr (.move_ (.var 3)) (.move_ (.var 4)))
        .return_)))
}

def BfIntersectionFun : LLBCFunDef := {
  name   := "bf_intersection"
  params := [⟨1, .uint .U32, some "a"⟩, ⟨2, .uint .U32, some "b"⟩]
  locals := [
    ⟨0, .uint .U32, none⟩,
    ⟨1, .uint .U32, some "a"⟩,
    ⟨2, .uint .U32, some "b"⟩,
    ⟨3, .uint .U32, none⟩,
    ⟨4, .uint .U32, none⟩]
  retTy  := .uint .U32
  body   :=
    (.assign (.var 3) (.use (.copy (.var 1)))
    (.assign (.var 4) (.use (.copy (.var 2)))
      (.assign (.var 0) (.binOp .bitAnd (.move_ (.var 3)) (.move_ (.var 4)))
        .return_)))
}

def BfSymmetricDiffFun : LLBCFunDef := {
  name   := "bf_symmetric_diff"
  params := [⟨1, .uint .U32, some "a"⟩, ⟨2, .uint .U32, some "b"⟩]
  locals := [
    ⟨0, .uint .U32, none⟩,
    ⟨1, .uint .U32, some "a"⟩,
    ⟨2, .uint .U32, some "b"⟩,
    ⟨3, .uint .U32, none⟩,
    ⟨4, .uint .U32, none⟩]
  retTy  := .uint .U32
  body   :=
    (.assign (.var 3) (.use (.copy (.var 1)))
    (.assign (.var 4) (.use (.copy (.var 2)))
      (.assign (.var 0) (.binOp .bitXor (.move_ (.var 3)) (.move_ (.var 4)))
        .return_)))
}

end LeanPlVerify.LLBC.Charon
