/-
  Translation/CharonSpec.lean

  Theorems for the Charon-extracted LLBCFunDef terms in CharonDefs.lean.

  This file proves the SAME functional-correctness properties as ElabSpec.lean,
  but against LLBCFunDef terms that were AUTOMATICALLY GENERATED by the pipeline:

    verified_fns.rs  →  charon cargo  →  verified_fns.llbc  →  charon2lean.py  →  CharonDefs.lean

  The proof shapes are identical to ElabSpec.lean:
    · Straight-line:  ⟨witness, (), rfl, rfl⟩
    · With overflow:  refine ⟨…, (), ?_, rfl⟩; simp[…]; rw [if_pos h]; rfl
    · Branching:      simp [decide_eq_true h]  /  simp [decide_eq_false …]
    · Ground numeric: ⟨.int N, (), rfl, rfl⟩

  Key difference from ElabSpec: Charon emits more temporaries (explicit copy
  locals for operands, overflow-check booleans from AddChecked/SubChecked).
  These extra locals are "dead" for the proofs — the simp reduction passes
  through them transparently.

  C17 (pow): 5 theorems — pow_zero (symbolic), ground instances ×3, nocrash.
  C18 (gcd): 5 theorems — gcd_zero (symbolic), ground instances ×3, nocrash.

  Theorem count: 57, sorry count: 0.
-/

import Mathlib.Tactic
import LeanPlVerify.Translation.CharonDefs
import LeanPlVerify.Spec.Satisfies

namespace LeanPlVerify.LLBC.CharonSpec

open LeanPlVerify LeanPlVerify.LLBC LeanPlVerify.LLBC.Charon

-- Shared simp set for all Charon proofs
macro "charon_simp" args:Lean.Parser.Tactic.simpLemma,* : tactic =>
  `(tactic| simp only [evalFun, evalFunBody, evalStmtFuel, buildLocals,
              evalRValuePure, evalBinOpPure, evalOperandPure, evalPlacePure,
              writePlacePure, evalLit,
              List.replicate, List.foldl, List.zipWith, List.set, List.find?,
              beq_self_eq_true, getElem?_pos, List.getElem_cons_succ, List.getElem_cons_zero,
              List.length_cons, List.length_nil,
              Nat.reduceAdd, Nat.reduceLT, Nat.zero_add, $args,*])

-- ════════════════════════════════════════════════════════════════════════════
-- C1: return42
-- ════════════════════════════════════════════════════════════════════════════

#eval evalFun [] Return42Fun 10 [] ()

theorem charon_return42 :
    evalFun [] Return42Fun 10 [] at () |= .pureOutput (· = .int 42) :=
  ⟨.int 42, (), rfl, rfl⟩

-- ════════════════════════════════════════════════════════════════════════════
-- C2: id
-- ════════════════════════════════════════════════════════════════════════════

#eval evalFun [] IdFun 10 [.int 7] ()

theorem charon_id (x : Int) :
    evalFun [] IdFun 10 [.int x] at () |= .pureOutput (· = .int x) :=
  ⟨.int x, (), rfl, rfl⟩

-- ════════════════════════════════════════════════════════════════════════════
-- C3: neg
-- Charon adds an overflow-check local (var 3 = (x == I32::MIN)).
-- var 3 is dead for var 0; simp passes through transparently.
-- ════════════════════════════════════════════════════════════════════════════

#eval evalFun [] NegFun 10 [.int 5] ()
#eval evalFun [] NegFun 10 [.int (-3)] ()

theorem charon_neg (x : Int) :
    evalFun [] NegFun 10 [.int x] at () |= .pureOutput (· = .int (-x)) := by
  refine ⟨.int (-x), (), ?_, rfl⟩
  charon_simp NegFun

-- ════════════════════════════════════════════════════════════════════════════
-- C4: add  (overflow guard)
-- ════════════════════════════════════════════════════════════════════════════

#eval evalFun [] AddFun 10 [.int 3, .int 4] ()

theorem charon_add (x y : Int)
    (h : IntBounds.minI32 ≤ x + y ∧ x + y ≤ IntBounds.maxI32) :
    evalFun [] AddFun 10 [.int x, .int y] at () |= .pureOutput (· = .int (x + y)) := by
  refine ⟨.int (x + y), (), ?_, rfl⟩
  charon_simp AddFun
  rw [if_pos h]; rfl

theorem charon_add_nocrash (x y : Int)
    (h : IntBounds.minI32 ≤ x + y ∧ x + y ≤ IntBounds.maxI32) :
    evalFun [] AddFun 10 [.int x, .int y] at () |= .nocrash :=
  sat_pureOutput_nocrash (charon_add x y h)

-- ════════════════════════════════════════════════════════════════════════════
-- C5: sub  (overflow guard)
-- ════════════════════════════════════════════════════════════════════════════

theorem charon_sub (x y : Int)
    (h : IntBounds.minI32 ≤ x - y ∧ x - y ≤ IntBounds.maxI32) :
    evalFun [] SubFun 10 [.int x, .int y] at () |= .pureOutput (· = .int (x - y)) := by
  refine ⟨.int (x - y), (), ?_, rfl⟩
  charon_simp SubFun
  rw [if_pos h]; rfl

-- ════════════════════════════════════════════════════════════════════════════
-- C6: max  (branching; Charon adds copy temporaries for a, b)
-- ════════════════════════════════════════════════════════════════════════════

#eval evalFun [] MaxFun 10 [.int 5, .int 3] ()
#eval evalFun [] MaxFun 10 [.int 2, .int 7] ()

theorem charon_max_ge (a b : Int) (h : a ≥ b) :
    evalFun [] MaxFun 10 [.int a, .int b] at () |= .pureOutput (· = .int a) := by
  refine ⟨.int a, (), ?_, rfl⟩
  charon_simp MaxFun, decide_eq_true h

theorem charon_max_lt (a b : Int) (h : a < b) :
    evalFun [] MaxFun 10 [.int a, .int b] at () |= .pureOutput (· = .int b) := by
  refine ⟨.int b, (), ?_, rfl⟩
  have hf : decide (a ≥ b) = false := decide_eq_false (not_le.mpr h)
  charon_simp MaxFun, hf

theorem charon_max_either (a b : Int) :
    evalFun [] MaxFun 10 [.int a, .int b] at () |=
      .pureOutput (fun v => v = .int a ∨ v = .int b) := by
  rcases Classical.em (a ≥ b) with h | h
  · exact sat_pureOutput_mono (fun _ hv => Or.inl hv) (charon_max_ge a b h)
  · exact sat_pureOutput_mono (fun _ hv => Or.inr hv) (charon_max_lt a b (not_le.mp h))

theorem charon_max_ge_both (a b : Int) :
    evalFun [] MaxFun 10 [.int a, .int b] at () |=
      .pureOutput (fun v => ∃ n : Int, v = .int n ∧ n ≥ a ∧ n ≥ b) := by
  rcases Classical.em (a ≥ b) with h | h
  · exact sat_pureOutput_mono (fun v hv => ⟨a, hv, le_refl a, h⟩) (charon_max_ge a b h)
  · exact sat_pureOutput_mono
        (fun v hv => ⟨b, hv, le_of_lt (not_le.mp h), le_refl b⟩)
        (charon_max_lt a b (not_le.mp h))

-- ════════════════════════════════════════════════════════════════════════════
-- C7: abs
-- ════════════════════════════════════════════════════════════════════════════

theorem charon_abs_nonneg (x : Int) (h : x ≥ 0) :
    evalFun [] AbsFun 10 [.int x] at () |= .pureOutput (· = .int x) := by
  refine ⟨.int x, (), ?_, rfl⟩
  charon_simp AbsFun, decide_eq_true h

theorem charon_abs_neg (x : Int) (h : x < 0) :
    evalFun [] AbsFun 10 [.int x] at () |= .pureOutput (· = .int (-x)) := by
  refine ⟨.int (-x), (), ?_, rfl⟩
  have hf : decide (x ≥ 0) = false := decide_eq_false (not_le.mpr h)
  charon_simp AbsFun, hf

theorem charon_abs_nonneg_result (x : Int) :
    evalFun [] AbsFun 10 [.int x] at () |=
      .pureOutput (fun v => ∃ n : Int, v = .int n ∧ n ≥ 0) := by
  rcases Classical.em (x ≥ 0) with h | h
  · exact sat_pureOutput_mono (fun v hv => ⟨x, hv, h⟩) (charon_abs_nonneg x h)
  · exact sat_pureOutput_mono
        (fun v hv => ⟨-x, hv, neg_nonneg.mpr (le_of_lt (not_le.mp h))⟩)
        (charon_abs_neg x (not_le.mp h))

-- ════════════════════════════════════════════════════════════════════════════
-- C8: is_zero
-- ════════════════════════════════════════════════════════════════════════════

theorem charon_isZero_zero :
    evalFun [] IsZeroFun 10 [.int 0] at () |= .pureOutput (· = .bool_ true) :=
  ⟨.bool_ true, (), rfl, rfl⟩

theorem charon_isZero_nonzero (x : Int) (hx : x ≠ 0) :
    evalFun [] IsZeroFun 10 [.int x] at () |= .pureOutput (· = .bool_ false) := by
  refine ⟨.bool_ false, (), ?_, rfl⟩
  charon_simp IsZeroFun
  simp [show (x == (0 : Int)) = false from by simpa using hx]

-- ════════════════════════════════════════════════════════════════════════════
-- C9: not_gate
-- ════════════════════════════════════════════════════════════════════════════

theorem charon_not_gate (b : Bool) :
    evalFun [] NotGateFun 10 [.bool_ b] at () |= .pureOutput (· = .bool_ !b) :=
  ⟨.bool_ !b, (), rfl, rfl⟩

theorem charon_not_involution (b : Bool) :
    evalFun [] NotGateFun 10 [.bool_ b] at () |=
      .pureOutput (fun v => evalFun [] NotGateFun 10 [v] at () |=
                              .pureOutput (· = .bool_ b)) :=
  sat_pureOutput_mono
    (fun v hv => by subst hv; cases b <;> exact ⟨_, (), rfl, rfl⟩)
    (charon_not_gate b)

-- ════════════════════════════════════════════════════════════════════════════
-- C10: clamp
-- ════════════════════════════════════════════════════════════════════════════

theorem charon_clamp_mid (x lo hi : Int) (h1 : lo ≤ x) (h2 : x ≤ hi) :
    evalFun [] ClampFun 50 [.int x, .int lo, .int hi] at () |= .pureOutput (· = .int x) := by
  refine ⟨.int x, (), ?_, rfl⟩
  have hlt : decide (x < lo) = false := decide_eq_false (not_lt.mpr h1)
  have hgt : decide (x > hi) = false := decide_eq_false (not_lt.mpr h2)
  charon_simp ClampFun, hlt, hgt

theorem charon_clamp_lo (x lo hi : Int) (h : x < lo) :
    evalFun [] ClampFun 50 [.int x, .int lo, .int hi] at () |= .pureOutput (· = .int lo) := by
  refine ⟨.int lo, (), ?_, rfl⟩
  charon_simp ClampFun, decide_eq_true h

theorem charon_clamp_hi (x lo hi : Int) (h1 : lo ≤ x) (h2 : hi < x) :
    evalFun [] ClampFun 50 [.int x, .int lo, .int hi] at () |= .pureOutput (· = .int hi) := by
  refine ⟨.int hi, (), ?_, rfl⟩
  have hlt : decide (x < lo) = false := decide_eq_false (not_lt.mpr h1)
  charon_simp ClampFun, hlt, decide_eq_true h2

theorem charon_clamp_inrange (x lo hi : Int) (h : lo ≤ hi) :
    evalFun [] ClampFun 50 [.int x, .int lo, .int hi] at () |=
      .pureOutput (fun v => ∃ n : Int, v = .int n ∧ lo ≤ n ∧ n ≤ hi) := by
  rcases lt_trichotomy x lo with hlt | heq | hgt
  · exact sat_pureOutput_mono (fun v hv => ⟨lo, hv, le_refl lo, h⟩)
        (charon_clamp_lo x lo hi hlt)
  · rw [heq]
    exact sat_pureOutput_mono (fun v hv => ⟨lo, hv, le_refl lo, h⟩)
        (charon_clamp_mid lo lo hi (le_refl lo) h)
  · rcases Classical.em (x ≤ hi) with hle | hlt
    · exact sat_pureOutput_mono (fun v hv => ⟨x, hv, le_of_lt hgt, hle⟩)
          (charon_clamp_mid x lo hi (le_of_lt hgt) hle)
    · exact sat_pureOutput_mono (fun v hv => ⟨hi, hv, h, le_refl hi⟩)
          (charon_clamp_hi x lo hi (le_of_lt hgt) (not_le.mp hlt))

-- ════════════════════════════════════════════════════════════════════════════
-- C11: sum_to  (ground numeric instances via rfl)
-- ════════════════════════════════════════════════════════════════════════════

#eval evalFun [] SumToFun 1000 [.int 5]  ()   -- 10
#eval evalFun [] SumToFun 1000 [.int 10] ()   -- 45

theorem charon_sumTo_zero :
    evalFun [] SumToFun 1000 [.int 0] at () |= .pureOutput (· = .int 0) :=
  ⟨.int 0, (), rfl, rfl⟩

theorem charon_sumTo_one :
    evalFun [] SumToFun 1000 [.int 1] at () |= .pureOutput (· = .int 0) :=
  ⟨.int 0, (), rfl, rfl⟩

theorem charon_sumTo_five :
    evalFun [] SumToFun 1000 [.int 5] at () |= .pureOutput (· = .int 10) :=
  ⟨.int 10, (), rfl, rfl⟩

theorem charon_sumTo_ten :
    evalFun [] SumToFun 1000 [.int 10] at () |= .pureOutput (· = .int 45) :=
  ⟨.int 45, (), rfl, rfl⟩

theorem charon_sumTo_nocrash_zero :
    evalFun [] SumToFun 1000 [.int 0] at () |= .nocrash :=
  sat_pureOutput_nocrash charon_sumTo_zero

theorem charon_sumTo_nocrash_ten :
    evalFun [] SumToFun 1000 [.int 10] at () |= .nocrash :=
  sat_pureOutput_nocrash charon_sumTo_ten

-- ════════════════════════════════════════════════════════════════════════════
-- C12: fact
-- ════════════════════════════════════════════════════════════════════════════

#eval evalFun [] FactFun 10000 [.int 5]  ()   -- 120
#eval evalFun [] FactFun 10000 [.int 10] ()   -- 3628800

theorem charon_fact_zero :
    evalFun [] FactFun 10000 [.int 0] at () |= .pureOutput (· = .int 1) :=
  ⟨.int 1, (), rfl, rfl⟩

theorem charon_fact_one :
    evalFun [] FactFun 10000 [.int 1] at () |= .pureOutput (· = .int 1) :=
  ⟨.int 1, (), rfl, rfl⟩

theorem charon_fact_five :
    evalFun [] FactFun 10000 [.int 5] at () |= .pureOutput (· = .int 120) :=
  ⟨.int 120, (), rfl, rfl⟩

theorem charon_fact_ten :
    evalFun [] FactFun 10000 [.int 10] at () |= .pureOutput (· = .int 3628800) :=
  ⟨.int 3628800, (), rfl, rfl⟩

theorem charon_fact_nocrash_five :
    evalFun [] FactFun 10000 [.int 5] at () |= .nocrash :=
  sat_pureOutput_nocrash charon_fact_five

-- ════════════════════════════════════════════════════════════════════════════
-- C13: mul  (overflow guard)
-- ════════════════════════════════════════════════════════════════════════════

theorem charon_mul (x y : Int)
    (h : IntBounds.minI32 ≤ x * y ∧ x * y ≤ IntBounds.maxI32) :
    evalFun [] MulFun 10 [.int x, .int y] at () |= .pureOutput (· = .int (x * y)) := by
  refine ⟨.int (x * y), (), ?_, rfl⟩
  charon_simp MulFun
  rw [if_pos h]; rfl

theorem charon_mul_nocrash (x y : Int)
    (h : IntBounds.minI32 ≤ x * y ∧ x * y ≤ IntBounds.maxI32) :
    evalFun [] MulFun 10 [.int x, .int y] at () |= .nocrash :=
  sat_pureOutput_nocrash (charon_mul x y h)

-- ════════════════════════════════════════════════════════════════════════════
-- C14: min
-- ════════════════════════════════════════════════════════════════════════════

theorem charon_min_le (a b : Int) (h : a ≤ b) :
    evalFun [] MinFun 10 [.int a, .int b] at () |= .pureOutput (· = .int a) := by
  refine ⟨.int a, (), ?_, rfl⟩
  charon_simp MinFun, decide_eq_true h

theorem charon_min_gt (a b : Int) (h : a > b) :
    evalFun [] MinFun 10 [.int a, .int b] at () |= .pureOutput (· = .int b) := by
  refine ⟨.int b, (), ?_, rfl⟩
  have hf : decide (a ≤ b) = false := decide_eq_false (not_le.mpr h)
  charon_simp MinFun, hf

theorem charon_min_either (a b : Int) :
    evalFun [] MinFun 10 [.int a, .int b] at () |=
      .pureOutput (fun v => v = .int a ∨ v = .int b) := by
  rcases Classical.em (a ≤ b) with h | h
  · exact sat_pureOutput_mono (fun _ hv => Or.inl hv) (charon_min_le a b h)
  · exact sat_pureOutput_mono (fun _ hv => Or.inr hv) (charon_min_gt a b (not_le.mp h))

-- ════════════════════════════════════════════════════════════════════════════
-- C15: square  (cross-function call: square(x) = mul(x, x))
-- ════════════════════════════════════════════════════════════════════════════

#eval evalFun [MulFun] SquareFun 10 [.int 5]    ()   -- 25
#eval evalFun [MulFun] SquareFun 10 [.int (-4)] ()   -- 16

theorem charon_square_zero :
    evalFun [MulFun] SquareFun 10 [.int 0] at () |= .pureOutput (· = .int 0) :=
  ⟨.int 0, (), rfl, rfl⟩

theorem charon_square_five :
    evalFun [MulFun] SquareFun 10 [.int 5] at () |= .pureOutput (· = .int 25) :=
  ⟨.int 25, (), rfl, rfl⟩

theorem charon_square_neg4 :
    evalFun [MulFun] SquareFun 10 [.int (-4)] at () |= .pureOutput (· = .int 16) :=
  ⟨.int 16, (), rfl, rfl⟩

theorem charon_square_five_nonneg :
    evalFun [MulFun] SquareFun 10 [.int 5] at () |=
      .pureOutput (fun v => ∃ n : Int, v = .int n ∧ n ≥ 0) :=
  sat_pureOutput_mono (fun v hv => ⟨25, hv, by norm_num⟩) charon_square_five

-- ════════════════════════════════════════════════════════════════════════════
-- C16: fib  (ground numeric instances)
-- ════════════════════════════════════════════════════════════════════════════

#eval evalFun [] FibFun 1000 [.int 5]  ()   -- 5
#eval evalFun [] FibFun 1000 [.int 10] ()   -- 55

theorem charon_fib_zero :
    evalFun [] FibFun 1000 [.int 0] at () |= .pureOutput (· = .int 0) :=
  ⟨.int 0, (), rfl, rfl⟩

theorem charon_fib_one :
    evalFun [] FibFun 1000 [.int 1] at () |= .pureOutput (· = .int 1) :=
  ⟨.int 1, (), rfl, rfl⟩

theorem charon_fib_two :
    evalFun [] FibFun 1000 [.int 2] at () |= .pureOutput (· = .int 1) :=
  ⟨.int 1, (), rfl, rfl⟩

theorem charon_fib_five :
    evalFun [] FibFun 1000 [.int 5] at () |= .pureOutput (· = .int 5) :=
  ⟨.int 5, (), rfl, rfl⟩

theorem charon_fib_ten :
    evalFun [] FibFun 1000 [.int 10] at () |= .pureOutput (· = .int 55) :=
  ⟨.int 55, (), rfl, rfl⟩

theorem charon_fib_nocrash_ten :
    evalFun [] FibFun 1000 [.int 10] at () |= .nocrash :=
  sat_pureOutput_nocrash charon_fib_ten

-- ════════════════════════════════════════════════════════════════════════════
-- C17: pow  (x^n via loop: result * x^(n-i) = x^n invariant)
-- New function added to demonstrate pipeline extensibility.
-- ════════════════════════════════════════════════════════════════════════════

#eval evalFun [] PowFun 200 [.int 2, .int 10]  ()   -- 1024
#eval evalFun [] PowFun 200 [.int 3, .int 4]   ()   -- 81

/-- pow(x, 0) = 1 for any x — the loop never executes (i=0, n=0 → 0<0 false). -/
theorem charon_pow_zero (x : Int) :
    evalFun [] PowFun 10 [.int x, .int 0] at () |= .pureOutput (· = .int 1) :=
  ⟨.int 1, (), rfl, rfl⟩

theorem charon_pow_two_five :
    evalFun [] PowFun 200 [.int 2, .int 5] at () |= .pureOutput (· = .int 32) :=
  ⟨.int 32, (), rfl, rfl⟩

theorem charon_pow_two_ten :
    evalFun [] PowFun 200 [.int 2, .int 10] at () |= .pureOutput (· = .int 1024) :=
  ⟨.int 1024, (), rfl, rfl⟩

theorem charon_pow_three_four :
    evalFun [] PowFun 200 [.int 3, .int 4] at () |= .pureOutput (· = .int 81) :=
  ⟨.int 81, (), rfl, rfl⟩

theorem charon_pow_nocrash_ten :
    evalFun [] PowFun 200 [.int 2, .int 10] at () |= .nocrash :=
  sat_pureOutput_nocrash charon_pow_two_ten

-- ════════════════════════════════════════════════════════════════════════════
-- C18: gcd  (Euclidean algorithm via Rem)
-- Demonstrates: (1) Rem operator in our evaluator, (2) Charon UB-check
-- locals (vars 10-13) pass through simp transparently as dead assignments.
-- ════════════════════════════════════════════════════════════════════════════

#eval evalFun [] GcdFun 200 [.int 12, .int 8]   ()   -- 4
#eval evalFun [] GcdFun 200 [.int 100, .int 75]  ()   -- 25

/-- gcd(a, 0) = a for any a — the while condition y≠0 is immediately false. -/
theorem charon_gcd_zero (a : Int) :
    evalFun [] GcdFun 10 [.int a, .int 0] at () |= .pureOutput (· = .int a) :=
  ⟨.int a, (), rfl, rfl⟩

theorem charon_gcd_12_8 :
    evalFun [] GcdFun 200 [.int 12, .int 8] at () |= .pureOutput (· = .int 4) :=
  ⟨.int 4, (), rfl, rfl⟩

theorem charon_gcd_100_75 :
    evalFun [] GcdFun 200 [.int 100, .int 75] at () |= .pureOutput (· = .int 25) :=
  ⟨.int 25, (), rfl, rfl⟩

theorem charon_gcd_35_21 :
    evalFun [] GcdFun 200 [.int 35, .int 21] at () |= .pureOutput (· = .int 7) :=
  ⟨.int 7, (), rfl, rfl⟩

theorem charon_gcd_nocrash_12_8 :
    evalFun [] GcdFun 200 [.int 12, .int 8] at () |= .nocrash :=
  sat_pureOutput_nocrash charon_gcd_12_8

end LeanPlVerify.LLBC.CharonSpec
