/-
  Translation/CharonDefs.lean

  LLBCFunDef terms AUTO-GENERATED by charon2lean.py from:
    examples/verified_fns.llbc  (produced by `charon cargo`)

  Do NOT edit this file by hand — regenerate with:
    python3 charon2lean.py examples/verified_fns.llbc \
            LeanPlVerify/Translation/CharonDefs.lean

  Charon version: 0.1.197
  Crate: verified_fns
-/

import LeanPlVerify.Translation.Elaborator

namespace LeanPlVerify.LLBC.Charon

open LeanPlVerify.LLBC

def Return42Fun : LLBCFunDef := {
  name   := "return42"
  params := []
  locals := [
    ⟨0, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 0) (.use (.const (.int 42 .I32)))
    .return_)
}

def IdFun : LLBCFunDef := {
  name   := "id"
  params := [⟨1, .int .I32, some "x"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "x"⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 0) (.use (.copy (.var 1)))
    .return_)
}

def NegFun : LLBCFunDef := {
  name   := "neg"
  params := [⟨1, .int .I32, some "x"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "x"⟩,
    ⟨2, .int .I32, none⟩,
    ⟨3, .bool_, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 2) (.use (.copy (.var 1)))
    (.assign (.var 3) (.binOp .eq (.copy (.var 2)) (.const (.int (-2147483648) .I32)))
      (.assign (.var 0) (.unOp .neg (.move_ (.var 2)))
        .return_)))
}

def AddFun : LLBCFunDef := {
  name   := "add"
  params := [⟨1, .int .I32, some "x"⟩, ⟨2, .int .I32, some "y"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "x"⟩,
    ⟨2, .int .I32, some "y"⟩,
    ⟨3, .int .I32, none⟩,
    ⟨4, .int .I32, none⟩,
    ⟨5, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 3) (.use (.copy (.var 1)))
    (.assign (.var 4) (.use (.copy (.var 2)))
      (.assign (.var 5) (.binOp .add (.copy (.var 3)) (.copy (.var 4)))
        (.assign (.var 0) (.use (.move_ (.var 5)))
          .return_))))
}

def SubFun : LLBCFunDef := {
  name   := "sub"
  params := [⟨1, .int .I32, some "x"⟩, ⟨2, .int .I32, some "y"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "x"⟩,
    ⟨2, .int .I32, some "y"⟩,
    ⟨3, .int .I32, none⟩,
    ⟨4, .int .I32, none⟩,
    ⟨5, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 3) (.use (.copy (.var 1)))
    (.assign (.var 4) (.use (.copy (.var 2)))
      (.assign (.var 5) (.binOp .sub (.copy (.var 3)) (.copy (.var 4)))
        (.assign (.var 0) (.use (.move_ (.var 5)))
          .return_))))
}

def MaxFun : LLBCFunDef := {
  name   := "max"
  params := [⟨1, .int .I32, some "a"⟩, ⟨2, .int .I32, some "b"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "a"⟩,
    ⟨2, .int .I32, some "b"⟩,
    ⟨3, .bool_, none⟩,
    ⟨4, .int .I32, none⟩,
    ⟨5, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 4) (.use (.copy (.var 1)))
    (.assign (.var 5) (.use (.copy (.var 2)))
      (.assign (.var 3) (.binOp .ge (.move_ (.var 4)) (.move_ (.var 5)))
        (.seq (.ite (.move_ (.var 3))
            (.assign (.var 0) (.use (.copy (.var 1)))
            .skip)
            (.assign (.var 0) (.use (.copy (.var 2)))
            .skip))
          .return_))))
}

def AbsFun : LLBCFunDef := {
  name   := "abs"
  params := [⟨1, .int .I32, some "x"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "x"⟩,
    ⟨2, .bool_, none⟩,
    ⟨3, .int .I32, none⟩,
    ⟨4, .int .I32, none⟩,
    ⟨5, .bool_, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 3) (.use (.copy (.var 1)))
    (.assign (.var 2) (.binOp .ge (.move_ (.var 3)) (.const (.int 0 .I32)))
      (.seq (.ite (.move_ (.var 2))
          (.assign (.var 0) (.use (.copy (.var 1)))
          .skip)
          (.assign (.var 4) (.use (.copy (.var 1)))
          (.assign (.var 5) (.binOp .eq (.copy (.var 4)) (.const (.int (-2147483648) .I32)))
            (.assign (.var 0) (.unOp .neg (.move_ (.var 4)))
              .skip))))
        .return_)))
}

def IsZeroFun : LLBCFunDef := {
  name   := "is_zero"
  params := [⟨1, .int .I32, some "x"⟩]
  locals := [
    ⟨0, .bool_, none⟩,
    ⟨1, .int .I32, some "x"⟩,
    ⟨2, .int .I32, none⟩]
  retTy  := .bool_
  body   :=
    (.assign (.var 2) (.use (.copy (.var 1)))
    (.assign (.var 0) (.binOp .eq (.move_ (.var 2)) (.const (.int 0 .I32)))
      .return_))
}

def NotGateFun : LLBCFunDef := {
  name   := "not_gate"
  params := [⟨1, .bool_, some "b"⟩]
  locals := [
    ⟨0, .bool_, none⟩,
    ⟨1, .bool_, some "b"⟩,
    ⟨2, .bool_, none⟩]
  retTy  := .bool_
  body   :=
    (.assign (.var 2) (.use (.copy (.var 1)))
    (.assign (.var 0) (.unOp .not (.move_ (.var 2)))
      .return_))
}

def ClampFun : LLBCFunDef := {
  name   := "clamp"
  params := [⟨1, .int .I32, some "x"⟩, ⟨2, .int .I32, some "lo"⟩, ⟨3, .int .I32, some "hi"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "x"⟩,
    ⟨2, .int .I32, some "lo"⟩,
    ⟨3, .int .I32, some "hi"⟩,
    ⟨4, .bool_, none⟩,
    ⟨5, .int .I32, none⟩,
    ⟨6, .int .I32, none⟩,
    ⟨7, .bool_, none⟩,
    ⟨8, .int .I32, none⟩,
    ⟨9, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 5) (.use (.copy (.var 1)))
    (.assign (.var 6) (.use (.copy (.var 2)))
      (.assign (.var 4) (.binOp .lt (.move_ (.var 5)) (.move_ (.var 6)))
        (.seq (.ite (.move_ (.var 4))
            (.assign (.var 0) (.use (.copy (.var 2)))
            .skip)
            (.assign (.var 8) (.use (.copy (.var 1)))
            (.assign (.var 9) (.use (.copy (.var 3)))
              (.assign (.var 7) (.binOp .gt (.move_ (.var 8)) (.move_ (.var 9)))
                (.ite (.move_ (.var 7))
                    (.assign (.var 0) (.use (.copy (.var 3)))
                    .skip)
                    (.assign (.var 0) (.use (.copy (.var 1)))
                    .skip))))))
          .return_))))
}

def SumToFun : LLBCFunDef := {
  name   := "sum_to"
  params := [⟨1, .int .I32, some "n"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "n"⟩,
    ⟨2, .int .I32, some "s"⟩,
    ⟨3, .int .I32, some "i"⟩,
    ⟨4, .bool_, none⟩,
    ⟨5, .int .I32, none⟩,
    ⟨6, .int .I32, none⟩,
    ⟨7, .int .I32, none⟩,
    ⟨8, .int .I32, none⟩,
    ⟨9, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 2) (.use (.const (.int 0 .I32)))
    (.assign (.var 3) (.use (.const (.int 0 .I32)))
      (.seq (.loop (.assign (.var 5) (.use (.copy (.var 3)))
          (.assign (.var 6) (.use (.copy (.var 1)))
            (.assign (.var 4) (.binOp .lt (.move_ (.var 5)) (.move_ (.var 6)))
              (.ite (.move_ (.var 4))
                  (.assign (.var 7) (.use (.copy (.var 3)))
                  (.assign (.var 8) (.binOp .add (.copy (.var 2)) (.copy (.var 7)))
                    (.assign (.var 2) (.use (.move_ (.var 8)))
                      (.assign (.var 9) (.binOp .add (.copy (.var 3)) (.const (.int 1 .I32)))
                        (.assign (.var 3) (.use (.move_ (.var 9)))
                          .continue_)))))
                  .break_)))))
        (.assign (.var 0) (.use (.copy (.var 2)))
        .return_))))
}

def FactFun : LLBCFunDef := {
  name   := "fact"
  params := [⟨1, .int .I32, some "n"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "n"⟩,
    ⟨2, .int .I32, some "acc"⟩,
    ⟨3, .int .I32, some "i"⟩,
    ⟨4, .bool_, none⟩,
    ⟨5, .int .I32, none⟩,
    ⟨6, .int .I32, none⟩,
    ⟨7, .int .I32, none⟩,
    ⟨8, .int .I32, none⟩,
    ⟨9, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 2) (.use (.const (.int 1 .I32)))
    (.assign (.var 3) (.use (.const (.int 1 .I32)))
      (.seq (.loop (.assign (.var 5) (.use (.copy (.var 3)))
          (.assign (.var 6) (.use (.copy (.var 1)))
            (.assign (.var 4) (.binOp .le (.move_ (.var 5)) (.move_ (.var 6)))
              (.ite (.move_ (.var 4))
                  (.assign (.var 7) (.use (.copy (.var 3)))
                  (.assign (.var 8) (.binOp .mul (.copy (.var 2)) (.copy (.var 7)))
                    (.assign (.var 2) (.use (.move_ (.var 8)))
                      (.assign (.var 9) (.binOp .add (.copy (.var 3)) (.const (.int 1 .I32)))
                        (.assign (.var 3) (.use (.move_ (.var 9)))
                          .continue_)))))
                  .break_)))))
        (.assign (.var 0) (.use (.copy (.var 2)))
        .return_))))
}

def MulFun : LLBCFunDef := {
  name   := "mul"
  params := [⟨1, .int .I32, some "x"⟩, ⟨2, .int .I32, some "y"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "x"⟩,
    ⟨2, .int .I32, some "y"⟩,
    ⟨3, .int .I32, none⟩,
    ⟨4, .int .I32, none⟩,
    ⟨5, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 3) (.use (.copy (.var 1)))
    (.assign (.var 4) (.use (.copy (.var 2)))
      (.assign (.var 5) (.binOp .mul (.copy (.var 3)) (.copy (.var 4)))
        (.assign (.var 0) (.use (.move_ (.var 5)))
          .return_))))
}

def MinFun : LLBCFunDef := {
  name   := "min"
  params := [⟨1, .int .I32, some "a"⟩, ⟨2, .int .I32, some "b"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "a"⟩,
    ⟨2, .int .I32, some "b"⟩,
    ⟨3, .bool_, none⟩,
    ⟨4, .int .I32, none⟩,
    ⟨5, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 4) (.use (.copy (.var 1)))
    (.assign (.var 5) (.use (.copy (.var 2)))
      (.assign (.var 3) (.binOp .le (.move_ (.var 4)) (.move_ (.var 5)))
        (.seq (.ite (.move_ (.var 3))
            (.assign (.var 0) (.use (.copy (.var 1)))
            .skip)
            (.assign (.var 0) (.use (.copy (.var 2)))
            .skip))
          .return_))))
}

def SquareFun : LLBCFunDef := {
  name   := "square"
  params := [⟨1, .int .I32, some "x"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "x"⟩,
    ⟨2, .int .I32, none⟩,
    ⟨3, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 2) (.use (.copy (.var 1)))
    (.assign (.var 3) (.use (.copy (.var 1)))
      (.call (.var 0) "mul" [(.move_ (.var 2)), (.move_ (.var 3))]
        .return_)))
}

def FibFun : LLBCFunDef := {
  name   := "fib"
  params := [⟨1, .int .I32, some "n"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "n"⟩,
    ⟨2, .int .I32, some "a"⟩,
    ⟨3, .int .I32, some "b"⟩,
    ⟨4, .int .I32, some "i"⟩,
    ⟨5, .bool_, none⟩,
    ⟨6, .int .I32, none⟩,
    ⟨7, .int .I32, none⟩,
    ⟨8, .int .I32, some "tmp"⟩,
    ⟨9, .int .I32, none⟩,
    ⟨10, .int .I32, none⟩,
    ⟨11, .int .I32, none⟩,
    ⟨12, .int .I32, none⟩,
    ⟨13, .int .I32, none⟩,
    ⟨14, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 2) (.use (.const (.int 0 .I32)))
    (.assign (.var 3) (.use (.const (.int 1 .I32)))
      (.assign (.var 4) (.use (.const (.int 0 .I32)))
        (.seq (.loop (.assign (.var 6) (.use (.copy (.var 4)))
            (.assign (.var 7) (.use (.copy (.var 1)))
              (.assign (.var 5) (.binOp .lt (.move_ (.var 6)) (.move_ (.var 7)))
                (.ite (.move_ (.var 5))
                    (.assign (.var 9) (.use (.copy (.var 2)))
                    (.assign (.var 10) (.use (.copy (.var 3)))
                      (.assign (.var 11) (.binOp .add (.copy (.var 9)) (.copy (.var 10)))
                        (.assign (.var 8) (.use (.move_ (.var 11)))
                          (.assign (.var 12) (.use (.copy (.var 3)))
                            (.assign (.var 2) (.use (.move_ (.var 12)))
                              (.assign (.var 13) (.use (.copy (.var 8)))
                                (.assign (.var 3) (.use (.move_ (.var 13)))
                                  (.assign (.var 14) (.binOp .add (.copy (.var 4)) (.const (.int 1 .I32)))
                                    (.assign (.var 4) (.use (.move_ (.var 14)))
                                      .continue_))))))))))
                    .break_)))))
          (.assign (.var 0) (.use (.copy (.var 2)))
          .return_)))))
}

def PowFun : LLBCFunDef := {
  name   := "pow"
  params := [⟨1, .int .I32, some "x"⟩, ⟨2, .int .I32, some "n"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "x"⟩,
    ⟨2, .int .I32, some "n"⟩,
    ⟨3, .int .I32, some "result"⟩,
    ⟨4, .int .I32, some "i"⟩,
    ⟨5, .bool_, none⟩,
    ⟨6, .int .I32, none⟩,
    ⟨7, .int .I32, none⟩,
    ⟨8, .int .I32, none⟩,
    ⟨9, .int .I32, none⟩,
    ⟨10, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 3) (.use (.const (.int 1 .I32)))
    (.assign (.var 4) (.use (.const (.int 0 .I32)))
      (.seq (.loop (.assign (.var 6) (.use (.copy (.var 4)))
          (.assign (.var 7) (.use (.copy (.var 2)))
            (.assign (.var 5) (.binOp .lt (.move_ (.var 6)) (.move_ (.var 7)))
              (.ite (.move_ (.var 5))
                  (.assign (.var 8) (.use (.copy (.var 1)))
                  (.assign (.var 9) (.binOp .mul (.copy (.var 3)) (.copy (.var 8)))
                    (.assign (.var 3) (.use (.move_ (.var 9)))
                      (.assign (.var 10) (.binOp .add (.copy (.var 4)) (.const (.int 1 .I32)))
                        (.assign (.var 4) (.use (.move_ (.var 10)))
                          .continue_)))))
                  .break_)))))
        (.assign (.var 0) (.use (.copy (.var 3)))
        .return_))))
}

def GcdFun : LLBCFunDef := {
  name   := "gcd"
  params := [⟨1, .int .I32, some "a"⟩, ⟨2, .int .I32, some "b"⟩]
  locals := [
    ⟨0, .int .I32, none⟩,
    ⟨1, .int .I32, some "a"⟩,
    ⟨2, .int .I32, some "b"⟩,
    ⟨3, .int .I32, some "x"⟩,
    ⟨4, .int .I32, some "y"⟩,
    ⟨5, .bool_, none⟩,
    ⟨6, .int .I32, none⟩,
    ⟨7, .int .I32, some "t"⟩,
    ⟨8, .int .I32, none⟩,
    ⟨9, .int .I32, none⟩,
    ⟨10, .bool_, none⟩,
    ⟨11, .bool_, none⟩,
    ⟨12, .bool_, none⟩,
    ⟨13, .bool_, none⟩,
    ⟨14, .int .I32, none⟩,
    ⟨15, .int .I32, none⟩]
  retTy  := .int .I32
  body   :=
    (.assign (.var 3) (.use (.copy (.var 1)))
    (.assign (.var 4) (.use (.copy (.var 2)))
      (.seq (.loop (.assign (.var 6) (.use (.copy (.var 4)))
          (.assign (.var 5) (.binOp .ne (.move_ (.var 6)) (.const (.int 0 .I32)))
            (.ite (.move_ (.var 5))
                (.assign (.var 8) (.use (.copy (.var 3)))
                (.assign (.var 9) (.use (.copy (.var 4)))
                  (.assign (.var 10) (.binOp .eq (.copy (.var 9)) (.const (.int 0 .I32)))
                    (.assign (.var 11) (.binOp .eq (.copy (.var 9)) (.const (.int (-1) .I32)))
                      (.assign (.var 12) (.binOp .eq (.copy (.var 8)) (.const (.int (-2147483648) .I32)))
                        (.assign (.var 13) (.binOp .bitAnd (.move_ (.var 11)) (.move_ (.var 12)))
                          (.assign (.var 7) (.binOp .rem (.move_ (.var 8)) (.move_ (.var 9)))
                            (.assign (.var 14) (.use (.copy (.var 4)))
                              (.assign (.var 3) (.use (.move_ (.var 14)))
                                (.assign (.var 15) (.use (.copy (.var 7)))
                                  (.assign (.var 4) (.use (.move_ (.var 15)))
                                    .continue_)))))))))))
                .break_))))
        (.assign (.var 0) (.use (.copy (.var 3)))
        .return_))))
}

end LeanPlVerify.LLBC.Charon
